# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translator/translator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.wordInput.setObjectName("wordInput")
        self.verticalLayout.addWidget(self.wordInput)
        self.languageBox = QtWidgets.QComboBox(self.centralwidget)
        self.languageBox.setObjectName("languageBox")
        self.verticalLayout.addWidget(self.languageBox)
        self.translateButton = QtWidgets.QPushButton(self.centralwidget)
        self.translateButton.setObjectName("translateButton")
        self.verticalLayout.addWidget(self.translateButton)
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Translator App"))
        self.wordInput.setPlaceholderText(_translate("MainWindow", "შეიყვანე სიტყვა..."))
        self.translateButton.setText(_translate("MainWindow", "თარგმნე"))
        self.resultLabel.setText(_translate("MainWindow", "თარგმანი გამოჩნდება აქ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
